### Collection GET
GET http://localhost:3000/users
Content-Type: application/json
Accept: text/xml
x-api-version: v2

### Collection POST
POST http://localhost:3000/users
Content-Type: application/json
Accept: application/json

{
  "username": "lea",
  "password": "tiger",
  "activated": true
}

### Item GET
GET http://localhost:3000/users/9
Content-Type: application/json
Accept: text/csv

### Item PATCH 
PATCH http://localhost:3000/users/9
Content-type: application/json
Accept: application/json

{
  "completed": true
}

### Item DELETE
DELETE http://localhost:3000/users/-1
