### Collection GET
GET http://localhost:3000/categories
Accept-Language: es
Accept: application/json

### Collection GET XML
GET http://localhost:3000/categories
Accept-Language: es
Accept: text/xml

### Collection GET CSV
GET http://localhost:3000/categories
Accept-Language: fr
Accept: text/csv

### Collection GET avec pagination
GET http://localhost:3000/categories?page=1&itemsPerPage=2
Content-Type: application/json
Accept-Language: en
Accept: application/json

### Single item
GET http://localhost:3000/categories/1
Accept-Language: fr-FR,fr;q=0.9
Accept: application/json

### Single item XML
GET http://localhost:3000/categories/2
Accept-Language: es-ES,es;q=0.9
Accept: text/xml


### Collection POST
POST http://localhost:3000/categories
Content-Type: application/json
Accept: text/xml

{
  "name": "Romance",
  "description": "Livres qui traitent des relations amoureuses."
}

### Item GET
GET http://localhost:3000/categories/4
Content-Type: application/json
Accept-Language: fr-FR,fr;q=0.9,en;q=0.8
Accept: application/json

### Item PATCH 
PATCH http://localhost:3000/categories/2
Content-type: application/json
Accept: text/xml

{
  "description": "Livres qui traitent des relations amoureuses et de l'amour."
}

### Item DELETE
DELETE http://localhost:3000/categories/-1
