### Collection GET
GET http://localhost:3000/books
Accept-Language: fr
Accept: application/json

### Collection GET avec pagination
GET http://localhost:3000/books?page=1&itemsPerPage=3
Accept-Language: es
Accept: application/json

### Test Format CSV
GET http://localhost:3000/books
Accept-Language: fr
Accept: text/csv

### Test Format XML
GET http://localhost:3000/books?page=1&itemsPerPage=2
Accept-Language: es
Accept: text/xml

### Collection POST
POST http://localhost:3000/books
Content-Type: application/json
Accept: application/json

{
  "name": "Livre",
  "date_of_publication": "2023-12-23",
  "synopsis": "Un très bon livre",
  "author_id": 2,
  "category_id": 3
}

### Item GET
GET http://localhost:3000/books/2
Accept-Language: fr
Accept: application/json

### Item PATCH 
PATCH http://localhost:3000/books/15
Content-Type: application/json
Accept: text/xml

{
  "synopsis": "Synopsis mis à jour"
}

### Item DELETE
DELETE http://localhost:3000/books/-1
