### Collection GET
GET http://localhost:3000/authors
Accept: : application/json

### Collection GET avec pagination HATEOAS
GET http://localhost:3000/authors?page=1&itemsPerPage=2
Content-Type: application/json

### Collection POST
POST http://localhost:3000/authors
Accept: text/csv
Content-Type: application/json

{
  "firstName": "Pierrick",
  "lastName": "Leclercq",
  "bio": "Autrice depuis son plus jeune âge",
  "birthDate": "2004-09-28",
  "nationality": "Française"
}

### Item GET
GET http://localhost:3000/authors/3
Accept: text/xml
Content-Type: application/json

### Item PATCH 
PATCH http://localhost:3000/authors/6
Accept: text/xml
Content-type: application/json

{
  "bio": "Biographie mise à jour"
}

### Item DELETE
DELETE http://localhost:3000/authors/9