### Collection GET
GET http://localhost:3000/categories
Content-Type: application/json

### Collection POST
POST http://localhost:3000/categories
Content-Type: application/json

{
  "name": "Romance",
  "description": "Livres qui traitent des relations amoureuses."
}

### Item GET
GET http://localhost:3000/categories/1
Content-Type: application/json

### Item PATCH 
PATCH http://localhost:3000/categories/1
Content-type: application/json

{
  "description": "Livres qui traitent des relations amoureuses et de l'amour."
}

### Item DELETE
DELETE http://localhost:3000/categories/-1
